[package]
name = "linux_network"
version = "0.1.0"
authors = ["Dmitry Safonov <dimanss47@dimanss47.net>"]

[dependencies]
error-chain = "^0.11.0"
libc = "^0.2.33"
log = "^0.3.8"
nix = "^0.9.0"
numeric_enums = { path = "../numeric_enums" }
