[package]
name = "linux_network"
version = "0.1.0"
authors = ["Dmitry Safonov <dimanss47@dimanss47.net>"]

[dependencies]
error-chain = "^0.11.0"
futures = { version = "0.1.18", optional = true }
interfaces = "^0.0.3"
log = "^0.3.8"
nix = "^0.9.0"
numeric_enums = { path = "../numeric_enums" }
pnet_packet = "^0.20.0"
seccomp = { version = "^0.1.1", optional = true }
