[package]
name = "ping6_datacommon"
version = "0.1.0"
authors = ["Dmitry Safonov <dimanss47@dimanss47.net>"]

[dependencies]
capabilities = "^0.3.0"
crc16 = "^0.3.4"
error-chain = "^0.11.0"
libc = "^0.2.31"
linux_network = { path = "../linux_network" }
log = "^0.3.8"
nix = "^0.9.0"
