[package]
name = "ping6_datacommon"
version = "0.1.0"
authors = ["Dmitry Safonov <dimanss47@dimanss47.net>"]

[dependencies]
capabilities = "^0.3.0"
error-chain = "^0.11.0"
linux_network = { path = "../linux_network" }
log = "^0.3.8"
nix = "^0.9.0"
seahash = "^3.0.5"
seccomp = "^0.1.1"
